#python -m torch.distributed.launch --nproc_per_node=8 src/main_pretrain.py --model-type albert-base-v2 --data-option with_ds_special_wo_none_augmented --batch-size 16 --max-length 1024 --gradient-accumulation-steps 1 --option emnlp_shuffle --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 11 --order_shuffle --delta-ds


#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none_no_prev_ds --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option no_prev_ds --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5 --sln 0.0
sleep 5s
#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none_augmented --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_ms_os_augment_all_pret_shuffle_every10_sln --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-16_g-1_d-with_ds_special_wo_none_augmented_ds-merged_w-100_lr-5e-05_tr-50_mt-5_o-emnlp_shuffle_ms-True_os-True_1234 --sln 0.5

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_ms_included_in_finetune_os_only_real --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-50_mt-5_o-pilot_shuffle_ms-False_os-True_1234 

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_idx_10_sgd_steplr_3 --pret_idx 10 --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_216k_sgd_steplr_3 --pret_idx 0 --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 1e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_216k_sgd_steplr_3 --pret_idx 0 --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_216k_sgd_steplr_3 --pret_idx 0 --num-train-epochs 200 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234

#ython -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_idx_50_sgd_steplr_3 --pret_idx 50 --num-train-epochs 200 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_idx_0_sgd_steplr_3 --pret_idx 0 --num-train-epochs 200 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_subset_20000_ms-True_os-True_sln-None_1234

#python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option emnlp_shuffle_every10_msos_select_pret_idx_50_sgd_steplr_3 --pret_idx 50 --num-train-epochs 200 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_subset_20000_ms-True_os-True_sln-None_1234



#albert-base-v2_b-16_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-50_mt-5_o-pilot_shuffle_every10_ms-True_os-True_1234
#--restore_pretrain albert-large-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-50_mt-5_o-pilot_shuffle_ms-True_os-False_1234

