python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option sgd_every10_msos_real_shuffle_ablation --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234  --pret_idx 60
sleep 5s
python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option sgd_every10_msos_real_shuffle_ablation --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234  --pret_idx 80
sleep 5s
python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option sgd_every10_msos_real_shuffle_ablation --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234  --pret_idx 100
sleep 5s
python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option sgd_every10_msos_real_shuffle_ablation --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234  --pret_idx 0
sleep 5s
python -m torch.distributed.launch --nproc_per_node=8 src/main_dst.py --model-type albert-base-v2 --data-option with_ds_special_wo_none --batch-size 16 --max-length 512 --gradient-accumulation-steps 1 --option sgd_every10_msos_real_shuffle_ablation --num-train-epochs 100 --warmup-steps 100 --ds-type merged --learning-rate 5e-5 --fp-16 --max-turn 5  --restore_pretrain albert-base-v2_b-8_g-1_d-with_ds_special_wo_none_ds-merged_w-100_lr-5e-05_tr-100_mt-5_o-emnlp_with_sgd_dataset_ms-True_os-True_sln-None_1234  --pret_idx 40
